stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/Telco_customer_churn.xlsx
    outs:
      - data/processed/telco_clean.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/telco_clean.csv
    outs:
      - model.pkl
